services:
  jackett:
    image: linuxserver/jackett:0.24.1985
    restart: unless-stopped
    ports: ["${NOOK_TS_IP}:9117:9117"]
    volumes:
      - ${NOOK_DATA}/apps/jackett/config:/config
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
