services:
  tautulli:
    image: linuxserver/tautulli:2.17.1
    restart: unless-stopped
    ports: ["${NOOK_TS_IP}:8181:8181"]
    volumes:
      - ${NOOK_DATA}/apps/tautulli/config:/config
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
