services:
  adguard-home:
    image: adguard/adguardhome:v0.107.76
    restart: unless-stopped
    ports: ["${NOOK_TS_IP}:3002:3000"]
    volumes:
      - ${NOOK_DATA}/apps/adguard-home/opt/adguardhome/work:/opt/adguardhome/work
      - ${NOOK_DATA}/apps/adguard-home/opt/adguardhome/conf:/opt/adguardhome/conf
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
