services:
  mongo:
    image: mongo:8.2.2
    restart: unless-stopped
    ports: ["${NOOK_TS_IP}:27017:27017"]
    volumes:
      - ${NOOK_DATA}/apps/mongodb/data/configdb:/data/configdb
      - ${NOOK_DATA}/apps/mongodb/data/db:/data/db
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
