services:
  databag:
    image: balzack/databag:0.1.18
    restart: unless-stopped
    ports: ["${NOOK_TS_IP}:7000:7000"]
    volumes:
      - ${NOOK_DATA}/apps/databag/data:/var/lib/databag
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
