services:
  lazylibrarian:
    image: linuxserver/lazylibrarian:version-169e669f
    restart: unless-stopped
    ports: ["${NOOK_TS_IP}:5299:5299"]
    volumes:
      - ${NOOK_DATA}/apps/lazylibrarian/config:/config
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
