services:
  wallabag:
    image: wallabag/wallabag:2.6.14
    restart: unless-stopped
    ports: ["${NOOK_TS_IP}:25661:80"]
    volumes:
      - ${NOOK_DATA}/apps/wallabag/images:/var/www/wallabag/web/assets/images
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
